#:schema https://docs.jj-vcs.dev/latest/config-schema.json

# Copy to repo use Gerrit to have automatic Change-Id appending.
# Edit the repo config with `jj config edit --repo`.
# Sadly there is no way to do this conditionally based on the current repo with
# the templating language.

[gerrit]
default-remote        = "origin"
default-remote-branch = "master"

[templates]
commit_trailers = """
    format_signed_off_by_trailer(self) ++
    if(
      !trailers.contains_key("Change-Id"),
      format_gerrit_change_id_trailer(self)
    )
"""

[revset-aliases]
"blacklist()" = "wip() | private()"
"pending()" = ".. ~ ::tags() ~ ::remote_bookmarks() ~ @ ~ private()"
"private()" = """
  description(glob:'private:*') |
  description(glob:'PRIVATE:*') |
  description('substring-i:"DO NOT MAIL"') |
  conflicts() |
  (empty() ~ merges())
"""
"wip()" = """
  description(glob:'wip:*') |
  description(glob:'WIP:*') |
  description(glob:'aba*') |
  description(glob:'abandon*')
"""

# By default, show the repo trunk, the remote bookmarks, and all remote tags. We
# don't want to change these in most cases, but in some repos it's useful.
"immutable_heads()" = "present(trunk()) | remote_bookmarks() | tags()"

# trunk() by default resolves to the latest 'main'/'master' remote bookmark. May
# require customization for repos like nixpkgs.
"trunk()" = "latest((present(main) | present(master)) & remote_bookmarks())"

# Collapsed trunk - removes full ancestry
"trunk_head()" = "heads(trunk())"

# All current open stacks of work
"work()" = "mine() & mutable() & ~immutable_heads()"

# Same as above but shows parents for a nice UI view
"work_ui()" = "work() | trunk_head()"

# All commits in current stack (linearized by @ ancestry)
# "stack_members()" = "ancestors(@, 1000) & work()";
# This version should handle detached commits better and does not assume
# @ is somewhere in the stack.
"stack_members()" = "ancestors(closest(work()), 1000) & work()"

# Root of current stack
# ::@ & enforces linearity
# Otherwise, it can be ambiguous and break if history is not linear.
"stack_root()" = "roots(::@ & stack_members())"

# Entire current stack
"stack()" = "stack_members()"

# Useful derived forms
"stack_tip()" = "heads(stack())"

# Open changes = current stack only
"open()" = "stack()"

# Ready to push
"ready()" = "open() ~ blacklist()"

[revsets]
log = "stack()"
