name: "Nix CI"
on:
    pull_request:
        paths-ignore:
            - "README.md"
            - "LICENSE.md"
            - ".forgejo/workflows/*"
    push:
        paths-ignore:
            - "README.md"
            - "LICENSE.md"
            - ".forgejo/workflows/*"
    schedule:
        # See `./update-flake-inputs.yml` for more details.
        - cron: "5 0 * * *" # Every day at 00:05. Keep ahead of `./update-flake-inputs.yml`.
    workflow_dispatch:

concurrency:
    group: nix-ci-${{ forgejo.ref_name }}
    cancel-in-progress: false

jobs:
    build-date:
        name: "Build: date"
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for date"
              run: nix build .#nixosConfigurations.date.config.system.build.toplevel --accept-flake-config --builders "" --print-build-logs

    build-kiwi:
        name: "Build: kiwi"
        runs-on: kiwi
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for kiwi"
              run: nix build .#nixosConfigurations.kiwi.config.system.build.toplevel --accept-flake-config --builders "" --print-build-logs

    # Until we setup a container for aarch64_darwin.
    # build-lime:
    #     name: "Build: lime"
    #     runs-on: plum
    #     steps:
    #         - uses: actions/checkout@v5
    #         - name: "Build configuration for lime"
    #           run: nix build .#darwinConfigurations.lime.config.system.build.toplevel --accept-flake-config --builders "" --no-link

    build-pear:
        name: "Build: pear"
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for pear"
              run: nix build .#nixosConfigurations.pear.config.system.build.toplevel --accept-flake-config --builders "" --no-link

    build-plum:
        name: "Build: plum"
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for plum"
              run: nix build .#nixosConfigurations.plum.config.system.build.toplevel --accept-flake-config --builders "" --print-build-logs

    build-yuzu:
        name: "Build: yuzu"
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for yuzu"
              run: nix build .#nixosConfigurations.yuzu.config.system.build.toplevel --accept-flake-config --builders "" --print-build-logs
