name: "Nix CI"
on:
    pull_request:
        paths-ignore:
            - "README.md"
            - "LICENSE.md"
            - ".forgejo/workflows/*"
    push:
        paths-ignore:
            - "README.md"
            - "LICENSE.md"
            - ".forgejo/workflows/*"
    schedule:
        # See `./update-flake-inputs.yml` for more details.
        - cron: "5 0 * * *" # Every day at 00:05. Keep ahead of `./update-flake-inputs.yml`.
    workflow_dispatch:

concurrency:
    group: nix-ci-${{ forgejo.ref_name }}
    cancel-in-progress: false

jobs:
    changes:
        name: Check for changes
        runs-on: plum
        outputs:
            date: ${{ steps.filter.outputs.date }}
            kiwi: ${{ steps.filter.outputs.kiwi }}
            lime: ${{ steps.filter.outputs.lime }}
            pear: ${{ steps.filter.outputs.pear }}
            plum: ${{ steps.filter.outputs.plum }}
            yuzu: ${{ steps.filter.outputs.yuzu }}
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - uses: https://github.com/dorny/paths-filter@v3
              id: filter
              with:
                  base: master
                  filters: |
                      shared: &shared
                        - modules/common/**
                        - flake.*
                        - lib/**
                        - modules/nix.nix
                        - modules/system.nix
                        - keys.nix
                        - yubikey.pub
                      servers: &servers
                        - modules/acme/**
                        - modules/nginx.nix
                      date:
                        - hosts/date/**
                        - modules/linux/**
                        - *shared
                      kiwi:
                        - hosts/kiwi/**
                        - modules/linux/**
                        - modules/dr-radka.nix
                        - *shared
                        - *servers
                      lime:
                        - hosts/lime/**
                        - modules/darwin/**
                        - *shared
                      pear:
                        - hosts/pear/**
                        - modules/linux/**
                        - *shared
                      plum:
                        - hosts/plum/**
                        - modules/linux/**
                        - modules/site.nix
                        - *shared
                        - *servers
                      yuzu:
                        - hosts/yuzu/**
                        - modules/linux/**
                        - *shared

    build-date:
        name: "Build: date"
        needs: changes
        if: needs.changes.outputs.date == 'true'
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for date"
              run: nix build .#nixosConfigurations.date.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link

    build-kiwi:
        name: "Build: kiwi"
        needs: changes
        if: needs.changes.outputs.kiwi == 'true'
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for kiwi"
              run: nix build .#nixosConfigurations.kiwi.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link

    # Until we setup a container for aarch64_darwin.
    # build-lime:
    #     name: "Build: lime"
    #     needs: changes
    #     if: needs.changes.outputs.lime == 'true'
    #     runs-on: plum
    #     steps:
    #         - uses: actions/checkout@v5
    #         - name: "Build configuration for lime"
    #           run: nix build .#darwinConfigurations.lime.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link

    build-pear:
        name: "Build: pear"
        needs: changes
        if: needs.changes.outputs.pear == 'true'
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for pear"
              run: nix build .#nixosConfigurations.pear.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link

    build-plum:
        name: "Build: plum"
        needs: changes
        if: needs.changes.outputs.plum == 'true'
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for plum"
              run: nix build .#nixosConfigurations.plum.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link

    build-yuzu:
        name: "Build: yuzu"
        needs: changes
        if: needs.changes.outputs.yuzu == 'true'
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
            - name: "Build configuration for yuzu"
              run: nix build .#nixosConfigurations.yuzu.config.system.build.toplevel --accept-flake-config --builders "" --fallback --no-link
