name: Nix CI
on:
    pull_request:
        paths-ignore:
            - "*.md"
    push:
        paths-ignore:
            - "*.md"
concurrency:
    cancel-in-progress: false
    group: nix-ci-${{ forgejo.ref_name }}
jobs:
    omnix-ci:
        name: "omnix ci run"
        runs-on: sloe
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: "omnix ci run"
              run: |
                  nix run github:juspay/omnix -- ci run --include-all-dependencies --github-output
                  cat result | jq .result.ROOT.build.byName
