name: "Update Flake Inputs"
on:
    schedule:
        # Unfortunately the `workflow_call` options aren't great so we'll solve
        # this with cron runs of `./nix-ci.yml` for now. I would prefer to handle
        # this automatically if it becomes easier.
        - cron: "0 0 * * *" # Every day at 00:00. Keep behind `./nix-ci.yml` cron.
    workflow_dispatch:

jobs:
    update-flake-inputs:
        name: "Update flake inputs"
        runs-on: plum
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0
            - name: "Update specific inputs"
              run: nix flake update opencode claude-code
            - name: "Commit and push changes"
              run: |
                  fj auth add-key plumjam ${{ secrets.FORGEJO_TOKEN }}

                  git config --global user.name "PlumJam [bot]"
                  git config --global user.email "forgejo-bot@plumj.am"

                  if [ -n "$(git status --porcelain flake.lock)" ]; then
                    git add flake.lock
                    git commit -m "nix: Update flake inputs for AI tools."
                    git push origin master
                    echo "Changes commited and pushed."
                  else
                    echo "No changes to push."
                  fi
