[inputs]
cade.url              = "gh:manic-systems/cade?ref=next"
disko.url             = "gh:nix-community/disko"
fenix.url             = "gh:nix-community/fenix"
gerrit.url            = "afnix:afnix/nix-gerrit"
gerrit-autosubmit.url = "plumjam:plumjam/gerrit-autosubmit"
grove.url             = "plumjam:grove-systems/grove"
harmonia.url          = "gh:nix-community/harmonia"
helium.url            = "gh:amaanq/helium-flake"
hjem.url              = "gh:feel-co/hjem"
homebrew.url          = "gh:zhaofengli/nix-homebrew"
homebrew-cask         = { type = "fetch", url = "gh:homebrew/homebrew-cask" }
homebrew-core         = { type = "fetch", url = "gh:homebrew/homebrew-core" }
inshellah.url         = "gh:manic-systems/inshellah"
llm-agents.url        = "gh:numtide/llm-agents.nix"
ncro.url              = "gh:manic-systems/ncro"
niri.url              = "gh:niri-wm/niri"
nix-index.url         = "gh:nix-community/nix-index-database"
nixos-core.url        = "gh:manic-systems/nixos-core"                         # NOTE: Don't bump until this is fixed! <https://github.com/manic-systems/nixos-core/issues/44>
nu-lint.url           = "cb:wvhulle/nu-lint"
nufmt.url             = "gh:nushell/nufmt"
os.url                = "gh:NixOS/nixpkgs/nixos-unstable-small"
os-darwin.url         = "gh:nix-darwin/nix-darwin/master"
os-wsl.url            = "gh:nix-community/NixOS-WSL/main"
parts.url             = "gh:hercules-ci/flake-parts"
qml-niri.url          = "gh:imiric/qml-niri/main"
quickshell.url        = "outfoxxed:outfoxxed/quickshell"
rio.url               = "gh:raphamorim/rio"
rom.url               = "gh:manic-systems/rom"
run0-sudo-shim.url    = "gh:LordGrimmauld/run0-sudo-shim"
sops.url              = "gh:Mic92/sops-nix"
tack.url              = "gh:manic-systems/tack"
treefmt.url           = "gh:numtide/treefmt-nix"
ublock                = { type = "fetch", url = "gh:imputnet/uBlock" }
zyouz.url             = "gh:plumj-am/zyouz/tmp"

# For local testing.
# grove.url = "git+file:///home/jam/projects/grove?ref=graft"

[shorturls]
afnix     = "git+https://git.afnix.fr/{path}"
cb        = "git+https://codeberg.org/{path}"
gh        = "github:{path}"
outfoxxed = "git+https://git.outfoxxed.me/{path}"
plumjam   = "git+ssh://forgejo@git.plumj.am/{path}"

[all_follow]
darwin      = "os-darwin"
fenix       = "fenix"
flake-parts = "parts"
nix-darwin  = "os-darwin"
nixpkgs     = "os"
nixpkgs-lib = "os"
quickshell  = "quickshell"
treefmt-nix = "treefmt"

[tack]
recomposable = true
