return {
	-- "andreasvc/vim-256noir",
	-- priority = 1000,
	-- lazy = false,
	-- config = function()
	-- 	ColorMyPencils("256_noir")
	--
	-- 	-- Custom highlight overrides for 256 noir theme
	-- 	local highlights = {
	-- 		"hi Normal cterm=NONE ctermfg=250 ctermbg=NONE gui=NONE guifg=#bcbcbc guibg=NONE",
	-- 		"hi Keyword cterm=NONE ctermfg=255 ctermbg=NONE gui=NONE guifg=#eeeeee guibg=NONE",
	-- 		"hi Constant cterm=NONE ctermfg=252 ctermbg=NONE gui=NONE guifg=#d0d0d0 guibg=NONE",
	-- 		"hi String cterm=NONE ctermfg=245 ctermbg=NONE gui=NONE guifg=#8a8a8a guibg=NONE",
	-- 		"hi Comment cterm=NONE ctermfg=240 ctermbg=NONE gui=NONE guifg=#585858 guibg=NONE",
	-- 		"hi Number cterm=NONE ctermfg=196 ctermbg=NONE gui=NONE guifg=#ff0000 guibg=NONE",
	-- 		"hi SignColumn cterm=NONE ctermfg=124 ctermbg=NONE gui=NONE guifg=#af0000 guibg=NONE",
	-- 		"hi SpellRare cterm=NONE ctermfg=124 ctermbg=NONE gui=NONE guifg=#af0000 guibg=NONE",
	-- 		"hi StatusLine cterm=bold ctermfg=245 ctermbg=233 gui=bold guifg=#8a8a8a guibg=#121212",
	-- 		"hi StatusLineNC cterm=NONE ctermfg=236 ctermbg=233 gui=NONE guifg=#303030 guibg=#121212",
	-- 		"hi Visual cterm=NONE ctermfg=250 ctermbg=236 gui=NONE guifg=#bcbcbc guibg=#303030",
	-- 		"hi Normal cterm=NONE ctermfg=Gray ctermbg=NONE",
	-- 		"hi Keyword cterm=NONE ctermfg=White ctermbg=NONE",
	-- 		"hi Constant cterm=NONE ctermfg=Gray ctermbg=NONE",
	-- 		"hi String cterm=NONE ctermfg=Gray ctermbg=NONE",
	-- 		"hi Comment cterm=NONE ctermfg=DarkGray ctermbg=NONE",
	-- 		"hi Number cterm=NONE ctermfg=Red ctermbg=NONE",
	-- 		"hi SignColumn cterm=NONE ctermfg=Red ctermbg=NONE",
	-- 		"hi SpellRare cterm=NONE ctermfg=Red ctermbg=NONE",
	-- 		"hi StatusLine cterm=bold ctermfg=Gray ctermbg=Black",
	-- 		"hi StatusLineNC cterm=NONE ctermfg=DarkGray ctermbg=Black",
	-- 		"hi Visual cterm=NONE ctermfg=Gray ctermbg=DarkGray",
	-- 	}
	--
	-- 	for _, hl in ipairs(highlights) do
	-- 		CMD(hl)
	-- 	end
	--
	-- 	ColorMyPencils("256_noir")
	-- 	DisableItalic()
	-- 	DisableBold()
	-- end,
}
