return {
	-- "catppuccin/nvim",
	-- name = "catppuccin",
	-- priority = 1000,
	-- opts = {
	-- 	flavour = "mocha", -- latte, frappe, macchiato, mocha
	-- 	background = { dark = "mocha" },
	-- 	transparent = true,
	-- 	term_colors = true,
	-- 	dim_inactive = {
	-- 		enabled = true,
	-- 		shade = "dark",
	-- 		percentage = 0.5,
	-- 	},
	-- 	show_end_of_buffer = true,
	-- 	integrations = {
	-- 		telescope = { enabled = true },
	-- 		mini = { enabled = true, indentscope_color = "lavender" },
	-- 		mason = true,
	-- 		harpoon = true,
	-- 		cmp = true,
	-- 		treesitter = true,
	-- 		which_key = true,
	-- 		gitsigns = true,
	-- 	},
	-- 	custom_highlights = function(colors)
	-- 		return {
	-- 			LineNr = { fg = colors.overlay1 },
	-- 		}
	-- 	end,
	-- },
	-- config = function()
	-- 	ColorMyPencils("catppuccin")
	-- end,
}
