return {
	-- "slugbyte/lackluster.nvim",
	-- lazy = false,
	-- priority = 1000,
	-- opts = {
	-- 	disable_plugin = {
	-- 		todo_comments = true,
	-- 	},
	-- 	tweak_ui = {
	-- 		disable_undercurl = true,
	-- 		enable_end_of_buffer = true,
	-- 	},
	-- 	tweak_background = {
	-- 		normal = "none",
	-- 		telescope = "none",
	-- 		menu = "none",
	-- 		popup = "none",
	-- 	},
	-- 	tweak_highlight = {
	-- 		["@function"] = {
	-- 			bold = true,
	-- 		},
	-- 		["@keyword"] = {
	-- 			bold = true,
	-- 		},
	-- 	},
	-- 	tweak_syntax = {
	-- 		comment = require("lackluster").color.gray5,
	-- 	},
	-- },
	-- config = function()
	-- 	ColorMyPencils("lackluster-mint")
	-- 	DisableItalic()
	-- end,
}
