return {
	-- "jesseleite/nvim-noirbuddy",
	-- dependencies = { { "tjdevries/colorbuddy.nvim" } },
	-- lazy = false,
	-- priority = 1000,
	-- opts = {
	-- 	preset = "minimal",
	-- 	colors = {
	-- 		-- primary = "#D5A6A8",
	-- 		-- secondary = "#FADADD"
	-- 	},
	-- 	styles = {
	-- 		italic = false,
	-- 		bold = true,
	-- 		underline = true,
	-- 		undercurl = false,
	-- 	},
	-- },
	-- config = function()
	-- 	ColorMyPencils("noirbuddy")
	-- 	DisableItalic()
	-- end,
}
