return {
	-- 	"zenbones-theme/zenbones.nvim",
	-- 	lazy = false,
	-- 	priority = 1000,
	-- 	init = function()
	-- 		vim.g.bones_compat = 1
	-- 		vim.g.zenbones_transparent_background = 0
	-- 		vim.g.zenbones_solid_line_nr = 1
	-- 		vim.g.zenbones_italic_comments = 0
	-- 		vim.g.zenbones_lighten_line_nr = 10000000000
	-- 		vim.g.zenbones_solid_float_border = true
	-- 		vim.g.colorize_diagnostic_underline_text = true
	-- 	end,
	-- 	config = function()
	-- 		ColorMyPencils("rosebones")
	-- 		DisableItalic()
	--
	-- 		-- Custom highlight overrides
	-- 		local highlights = {
	-- 			DiagnosticUnderlineHint = "gui=underline",
	-- 			DiagnosticUnderlineInfo = "gui=underline",
	-- 			DiagnosticUnderlineWarn = "gui=underline",
	-- 			DiagnosticUnderlineError = "gui=underline",
	-- 			["@markup.link"] = "gui=none",
	-- 		}
	--
	-- 		for group, opts in pairs(highlights) do
	-- 			CMD("hi " .. group .. " " .. opts)
	-- 		end
	-- 	end,
}
