return {
	-- "X3eRo0/dired.nvim",
	-- dependencies = { "MunifTanjim/nui.nvim" },
	-- keys = {
	-- 	{
	-- 		"<C-s>",
	-- 		function()
	-- 			if vim.bo.filetype == "dired" then
	-- 				CMD("DiredQuit")
	-- 			else
	-- 				CMD("Dired")
	-- 			end
	-- 		end,
	-- 		desc = "Open Dired",
	-- 	},
	-- 	{
	-- 		"-",
	-- 		":Dired<cr>",
	-- 		desc = "Open Dired",
	-- 	},
	-- },
	-- opts = {
	-- 	hide_details = false,
	-- 	sort_order = "dirs",
	-- 	show_icons = false,
	-- 	show_hidden = true,
	-- 	show_banner = true,
	-- },
}
