return {
	-- "mrcjkb/rustaceanvim",
	-- version = "^6",
	-- lazy = false,
	-- init = function()
	-- 	vim.g.rustaceanvim = {
	-- 		tools = {
	-- 			test_executor = "background",
	-- 		},
	-- 		server = {
	-- 			default_settings = {
	-- 				["rust-analyzer"] = {
	-- 					-- checkOnSave and diagnostics must be disabled for bacon-ls
	-- 					checkOnSave = {
	-- 						command = "clippy",
	-- 						enable = true,
	-- 					},
	-- 					diagnostics = {
	-- 						enable = true,
	-- 						experimental = {
	-- 							enable = true,
	-- 						},
	-- 						styleLints = {
	-- 							enable = true,
	-- 						},
	-- 					},
	-- 					hover = {
	-- 						actions = {
	-- 							references = {
	-- 								enable = true,
	-- 							},
	-- 						},
	-- 					},
	-- 					interpret = {
	-- 						tests = true,
	-- 					},
	-- 					cargo = {
	-- 						features = "all",
	-- 					},
	-- 					completion = {
	-- 						fullFunctionSignatures = {
	-- 							enable = true,
	-- 						},
	-- 					},
	-- 				},
	-- 			},
	-- 		},
	-- 		dap = {},
	-- 	}
	-- end,
}
