return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	event = "BufRead",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"javascript",
			"typescript",
			"svelte",
			"markdown",
			"css",
			"html",
			"lua",
			"vim",
			"json",
			"yaml",
			"vimdoc",
			"go",
			"http",
			"rust",
		},
		highlight = { enable = true },
		auto_install = true,
		indent = { enable = true },
	},
}
